# Generated by Django 5.1.7 on 2025-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_emailverification_email_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Иконка'),
        ),
    ]
